import Head from 'next/head'
import styles from '../styles/Home.module.css'
// import Link from 'next/link'
import { useRouter } from 'next/router'


export default function Home() {
  setTimeout(myFucntion , 500);
  const router = useRouter();
  function myFucntion(){
    router.push('/login')
  }
  return (
    <div className={styles.container}>
      <Head>
        <title>Ecommerce</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <div style = {{backgroundColor : "white" , opacity: 0.9,
  filter: "alpha(opacity=90)"}}>
        <h1 className={styles.title}>
          Welcome to Ecommerce
        </h1>
        <div style = {{display : "flex" , justifyContent: "center" , alignItems : "center"}}>
        {/* <Link href = '/login' >
        < button style = {{backgroundColor : "#1e90ff"}}>   
          Get started with Ecommerce     
        </button>
        </Link> */}
        </div> 
        </div>
      </main>
    </div>
  )
}
